-- 0011_receipts_and_growth.sql
-- A bill the customer can keep, the providers they want again, and the two growth levers the
-- spec asks for: referrals and promo codes.
--
-- Forward-only. Nothing in 0001-0010 is rewritten.

-- ---------------------------------------------------------------------------
-- Receipts
-- ---------------------------------------------------------------------------

-- PRODUCT_SPEC section 4 promises "receipts/invoices" and there was no such thing: a customer
-- could see what they paid inside the app and had nothing to keep, forward or claim against.
--
-- The numbers are snapshotted rather than joined at read time. A receipt is a statement of what
-- was charged on a given day; if a later correction changes the ledger, that is a credit note,
-- not a quiet edit to a document somebody has already filed.
create table invoices (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references jobs(id) on delete cascade,
  customer_id uuid not null references users(id),

  -- Human-facing and sequential per financial year, because that is what a receipt number is
  -- for. Generated by the service, unique here.
  number text not null,

  labour_paise bigint not null,
  visit_fee_paise bigint not null,
  material_paise bigint not null default 0,
  delivery_paise bigint not null default 0,
  platform_fee_paise bigint not null,
  protection_fee_paise bigint not null default 0,
  tax_paise bigint not null,
  total_paise bigint not null,
  -- What came back after the fact. Shown on the receipt so the number a customer sees matches
  -- the number that left their account.
  refunded_paise bigint not null default 0,

  -- Who did the work, as it should appear on the document.
  provider_name text not null,
  category_name text not null,
  -- Where the work happened, snapshotted: an address the customer later deletes must not change
  -- a receipt they already hold.
  service_address text,

  issued_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create unique index invoices_number_idx on invoices(number);
-- One receipt per job. A second would be a different document with a different purpose.
create unique index invoices_job_idx on invoices(job_id);
create index invoices_customer_idx on invoices(customer_id, issued_at desc);
create trigger invoices_updated before update on invoices for each row execute function set_updated_at();

-- A document somebody may have filed with their accounts is not deleted.
revoke delete on invoices from public;
alter table invoices enable row level security;

-- ---------------------------------------------------------------------------
-- Providers worth asking for again
-- ---------------------------------------------------------------------------

create table favourite_providers (
  customer_id uuid not null references users(id) on delete cascade,
  provider_id uuid not null references users(id) on delete cascade,
  -- Why they were saved, in the customer's own words. Optional, and never shown to the provider:
  -- it is a note to self, not a review.
  note text,
  created_at timestamptz not null default now(),
  primary key (customer_id, provider_id)
);

create index favourite_providers_customer_idx on favourite_providers(customer_id, created_at desc);
alter table favourite_providers enable row level security;

-- ---------------------------------------------------------------------------
-- Promo codes
-- ---------------------------------------------------------------------------

create type promo_kind as enum ('FLAT', 'PERCENT');

create table promo_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  kind promo_kind not null,
  -- FLAT: paise off. PERCENT: basis points, so 1000 is 10%.
  value int not null check (value > 0),
  -- A percentage without a ceiling is an unbounded liability.
  max_discount_paise bigint,
  min_order_paise bigint not null default 0,

  -- The discount is the platform's cost, never the provider's: a professional is paid what the
  -- accepted quote said whatever the customer paid. This column exists to make that explicit
  -- rather than leaving it to be inferred from the ledger.
  funded_by text not null default 'PLATFORM' check (funded_by = 'PLATFORM'),

  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  -- Null means no cap.
  max_redemptions int,
  max_per_customer int not null default 1,
  first_job_only boolean not null default false,
  redemption_count int not null default 0,

  active boolean not null default true,
  created_by uuid references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz,

  constraint promo_percent_needs_ceiling check (kind <> 'PERCENT' or max_discount_paise is not null)
);

create unique index promo_codes_code_idx on promo_codes(upper(code));
create trigger promo_codes_updated before update on promo_codes for each row execute function set_updated_at();

create table promo_redemptions (
  id uuid primary key default gen_random_uuid(),
  promo_id uuid not null references promo_codes(id),
  customer_id uuid not null references users(id),
  job_id uuid not null references jobs(id) on delete cascade,
  discount_paise bigint not null check (discount_paise > 0),
  created_at timestamptz not null default now()
);

-- A code is used once per booking, whatever a retried request thinks.
create unique index promo_redemptions_job_idx on promo_redemptions(job_id);
create index promo_redemptions_customer_idx on promo_redemptions(customer_id, promo_id);

revoke update, delete on promo_redemptions from public;
alter table promo_codes enable row level security;
alter table promo_redemptions enable row level security;

-- ---------------------------------------------------------------------------
-- Referrals
-- ---------------------------------------------------------------------------

create type referral_status as enum ('PENDING', 'QUALIFIED', 'REWARDED', 'REJECTED');

-- Everyone has a code from the moment they sign up; it is derived, not allocated, so there is
-- nothing to run out of.
alter table users add column if not exists referral_code text;
create unique index if not exists users_referral_code_idx on users(referral_code) where referral_code is not null;

create table referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid not null references users(id) on delete cascade,
  referred_id uuid not null references users(id) on delete cascade,
  code text not null,

  -- A referral only pays out once the new person actually completes a job. Rewarding a signup
  -- rewards signups, which is how a referral programme becomes a fraud programme.
  status referral_status not null default 'PENDING',
  qualifying_job_id uuid references jobs(id),
  reward_paise bigint not null default 0,
  rewarded_at timestamptz,
  rejection_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz,

  -- Nobody refers themselves.
  constraint referral_not_self check (referrer_id <> referred_id)
);

-- A person is referred once, by one person, ever.
create unique index referrals_referred_idx on referrals(referred_id);
create index referrals_referrer_idx on referrals(referrer_id, created_at desc);
create trigger referrals_updated before update on referrals for each row execute function set_updated_at();

alter table referrals enable row level security;

-- ---------------------------------------------------------------------------
-- What a booking was discounted by
-- ---------------------------------------------------------------------------

-- Recorded on the quote so the receipt, the ledger and the customer's screen all read from the
-- same number rather than each recomputing it.
alter table booking_quotes add column if not exists discount_paise bigint not null default 0;
alter table booking_quotes add column if not exists promo_code text;
